name: Java CI

on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Build with Maven 
        run: mvn --batch-mode --update-snapshots verify -P integration-tests
      
      - name: RCPTT logs
        uses: actions/upload-artifact@v2
        with:
          name: rcptt_logs
          path: tests/rcptt/*/target/results/aut-console-*.log
          retention-days: 5
    
      - name: Deploy 🚀
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: releng/org.eclipse.poosl.update/target/repository
          target-folder: nightly
  
      - name: Release Products
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: releng/org.eclipse.poosl.product/target/products/poosl-*.zip
          
                    
# To deploy product on tag, use following action:
# 
# https://github.com/marketplace/actions/upload-files-to-a-github-release
# Activation condition:
### if: ${{ startsWith(github.ref, 'refs/tags/') }}

# Question: how to generate body based on release content