name: Java CI

on:
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven 
        run: mvn --batch-mode --update-snapshots verify -P integration-tests
      - name: Deploy 🚀
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: releng/org.eclipse.poosl.update/target/repository
          target-folder: nightly

                    
# To deploy product on tag, use following action:
# 
# https://github.com/marketplace/actions/upload-files-to-a-github-release
# Activation condition:
### if: ${{ startsWith(github.ref, 'refs/tags/') }}

# Question: how to generate body based on release content